In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5,"heelo",2.5])

array(['1', '2', '3', '4', '5', 'heelo', '2.5'], dtype='<U32')

In [7]:
l=[[1,2,3],
  [4,5,6],
  [7,8,9]]


In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [14]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
arr=np.linspace(1,51,5)
arr

array([ 1. , 13.5, 26. , 38.5, 51. ])

In [26]:
np.random.rand(10)

array([0.36808832, 0.80783792, 0.90612199, 0.93950354, 0.94375251,
       0.86816903, 0.80313344, 0.8631165 , 0.74435135, 0.97957174])

In [28]:
np.random.randn(10)

array([ 1.96060845, -1.8686057 ,  0.01730549,  0.10850839,  2.02296011,
       -0.22875395,  0.52645432,  0.553761  ,  0.55411617,  0.92501474])

In [34]:
np.random.randint(10,20,10)

array([17, 16, 18, 13, 10, 10, 12, 17, 13, 19], dtype=int32)

In [47]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr.shape

(3, 3)

In [49]:
arr.size

9

In [51]:
arr.dtype

dtype('int64')

In [52]:
arr.min()

np.int64(1)

In [53]:
arr.max()

np.int64(9)

In [54]:
arr.sum()

np.int64(45)

In [56]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [57]:
arr.mean()

np.float64(5.0)

In [58]:
arr.std()

np.float64(2.581988897471611)

In [59]:
arr.argmax()

np.int64(8)

In [60]:
arr.argmin()

np.int64(0)

In [61]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [65]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])