In [1]:
import numpy as np

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [3]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [4]:
l=[10,20,30,40]
arr=np.array(l)

In [5]:
arr+10

array([20, 30, 40, 50])

In [6]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
arr2+5

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
a=np.arange(1,21)

In [11]:
slice=a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [13]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
a[4:6]*20

array([100, 120])

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
b=a.copy()

In [30]:
b[0]=99

In [31]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])