In [9]:
import numpy as np

In [10]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[9]

np.int64(20)

In [12]:
arr_slice=arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [13]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [15]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [16]:
collumselect=arr[:,3]
collumselect

array([ 4,  9, 14, 19, 24, 29])

In [18]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [21]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])